[language-server.tsgo]
command = "bun"
args = ["x", "-p", "@typescript/native-preview", "tsgo", "--lsp", "--stdio"]

[language-server.oxlint]
command = "bun"
args = ["x", "oxlint", "--lsp"]

[language-server.oxfmt]
command = "bun"
args = ["x", "oxfmt", "--lsp"]

[[language]]
name = "typescript"
auto-format = true
language-servers = [
  { name = "tsgo", except-features = ["format"] },
  { name = "oxlint", only-features = ["diagnostics", "code-action"] },
  { name = "oxfmt", only-features = ["format"] },
]

[[language]]
name = "tsx"
auto-format = true
language-servers = [
  { name = "tsgo", except-features = ["format"] },
  { name = "oxlint", only-features = ["diagnostics", "code-action"] },
  { name = "oxfmt", only-features = ["format"] },
]

[[language]]
name = "javascript"
auto-format = true
language-servers = [
  { name = "tsgo", except-features = ["format"] },
  { name = "oxlint", only-features = ["diagnostics", "code-action"] },
  { name = "oxfmt", only-features = ["format"] },
]

[[language]]
name = "jsx"
auto-format = true
language-servers = [
  { name = "tsgo", except-features = ["format"] },
  { name = "oxlint", only-features = ["diagnostics", "code-action"] },
  { name = "oxfmt", only-features = ["format"] },
]
